name: muslim_life_ai_demo
description: A High-Fidelity Investor Demo for MuslimLife AI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_lucide: 1.7.0
  flutter_animate: ^4.5.0
  glass_kit: ^3.0.0
  url_launcher: ^6.2.0
  intl: ^0.19.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  http: ^1.6.0
  geolocator: ^13.0.0
  permission_handler: ^11.0.0
  flutter_compass: ^0.8.0
  adhan: ^2.0.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/quran/
  fonts:
    - family: KFGQPCUthmanic
      fonts:
        - asset: assets/fonts/KFGQPC-Uthmanic-Script-HAFS.otf
